# wrangler.toml
node_compat = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "buildownai-waitlist"
database_id = "d4ba8b5d-3508-4a24-ba04-3fa44a6b585a"
