// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/7/2024, 6:14:27 PM
const configMerger = require("/Users/sebastianwessel/projekte/buildown_ai/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/sebastianwessel/projekte/buildown_ai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/plugins/**/*.{js,ts,mjs}","/Users/sebastianwessel/projekte/buildown_ai/composables/**/*.{js,ts,mjs}","/Users/sebastianwessel/projekte/buildown_ai/utils/**/*.{js,ts,mjs}","/Users/sebastianwessel/projekte/buildown_ai/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sebastianwessel/projekte/buildown_ai/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["25"] = "/Users/sebastianwessel/projekte/buildown_ai/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
